In [1]:
import pandas as pd
import numpy as np

In [2]:
s=pd.Series([10,20,30,40,50],index=["a","b","c","d","e"])
print(s)
print(s["c"])
print(s[2])

a    10
b    20
c    30
d    40
e    50
dtype: int64
30
30

C:\Users\lenovo\AppData\Local\Temp\ipykernel_8832\1261443236.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[2])

In [3]:
new=np.array([10,3,48,39,93,39,59,29,49,28,42,56])
df=new.reshape(4,3)
a=pd.DataFrame(df,index=["a","s","d","r"],columns=["A","b","c"])
# a.index(["a","b","c","d"])
print(a)

    A   b   c
a  10   3  48
s  39  93  39
d  59  29  49
r  28  42  56

In [4]:
# series by dictionary

dict={"Math":25,"Phy":45,"che":96}

d=pd.Series(dict)
print(d)

Math    25
Phy     45
che     96
dtype: int64

In [5]:
aa={
    "name":["a","b","c","g","l","o","k"],
    "Age":[10,20,30,45,29,34,10],
    "marks":[20,30,50,17,65,73,19]
}
x=pd.DataFrame(aa,index=["la","la","la","la","la","la","la"])
print(x)

   name  Age  marks
la    a   10     20
la    b   20     30
la    c   30     50
la    g   45     17
la    l   29     65
la    o   34     73
la    k   10     19

In [6]:
x.set_index("name", inplace=True)
# inplace == true means we are changing the original object

print(x)

      Age  marks
name
a      10     20
b      20     30
c      30     50
g      45     17
l      29     65
o      34     73
k      10     19

In [14]:
new=pd.DataFrame(aa)
print(new.head())

# shows first 5 rows


print(new.tail())
print()
# shows last 5 rows
print(new.shape)
print()

new.columns

new.info()

  name  Age  marks
0    a   10     20
1    b   20     30
2    c   30     50
3    g   45     17
4    l   29     65
  name  Age  marks
2    c   30     50
3    g   45     17
4    l   29     65
5    o   34     73
6    k   10     19

(7, 3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      object
 1   Age     7 non-null      int64
 2   marks   7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [15]:
new.describe()

             Age      marks
count   7.000000   7.000000
mean   25.428571  39.142857
std    12.882251  23.376830
min    10.000000  17.000000
25%    15.000000  19.500000
50%    29.000000  30.000000
75%    32.000000  57.500000
max    45.000000  73.000000

In [16]:
new[(new["Age"]>10) & (new["marks"]>20)]

  name  Age  marks
1    b   20     30
2    c   30     50
4    l   29     65
5    o   34     73

In [ ]:
new["Age"].value_counts()